### ISSUE TITLE
Automatically select all repositories in "show more"

### ISSUE THREAD

**Issue by cthoyt** [jrieke/year-on-github#6] opened 2021-01-07 20:48 UTC
I had quite a few to repositories to click outside of my own namespace. It would be nice if there was a button to do it automatically for me.

Anyway, this is super fun! Thanks for making this :) Grüße aus Bonn

**Comment by jrieke** [comment] 2021-01-07 21:05
Hey Charles, thanks for the kind words! ❤️

I thought about this already while building the app but decided against it. The problem is that Github has a pretty strict rate limit on API calls and if you automatically select all external repos, it will also query repos that a user made 1-2 commits to but that have 50k stars (which requires a LOT of API calls to figure out the new stars). So if I just automatically select all external repos then the app will very quickly run into the rate limits and would crash if many people use it :(

Closing this for now but if you have any more thoughts, let me know. Grüße aus Berlin!

**Closed by jrieke** 2021-01-07 21:05 UTC

**Comment by cthoyt** [comment] 2021-01-07 21:10
That's a totally good reason. Thanks for the info!
